pipeline {
    agent any
    
    environment {
        DOCKERFILE_PATH = "inventory_service/Dockerfile" // Relative path to Dockerfile
        IMAGE_NAME = "inventory-service:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Build Docker image using Dockerfile in the inventory_service directory
                    docker.build(IMAGE_NAME, "-f ${DOCKERFILE_PATH} inventory_service")
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run tests inside the Docker container
                    docker.image(IMAGE_NAME).inside {
                        sh 'pytest'
                    }
                }
            }
        }

        stage('Push to Docker Registry') {
            steps {
                script {
                    // Push the Docker image to the Docker registry
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub_id') {
                        docker.image(IMAGE_NAME).push()
                    }
                }
            }
        }
    }
}
