pipeline {
    agent any
    
    environment {
        DOCKERFILE_PATH = "inventory_service/Dockerfile"
        IMAGE_NAME = "inventory-service:${env.BUILD_NUMBER}"
        DOCKER_REPO = "samjohnoffl/devops"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    docker.build(IMAGE_NAME, "-f ${DOCKERFILE_PATH} inventory_service")
                }
            }
        }

        // Removed the Test stage

        stage('Push to Docker Registry') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub_id') {
                        docker.image(IMAGE_NAME).push("${env.BUILD_NUMBER}")
                        docker.image(IMAGE_NAME).push("latest")
                    }
                }
            }
        }
    }
}
