pipeline {
    agent any

    environment {
        DOCKERFILE_PATH = "inventory_service/Dockerfile"
        IMAGE_NAME = "attemptmaster/devops:inventory-service-${env.BUILD_NUMBER}"
        DOCKER_REPO = "attemptmaster/devops"
        DOCKER_CREDENTIALS_ID = 'attemptmaster' // Assuming this is the correct credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/johnsamuel05/supply-chain-management-devops.git'
            }
        }

        stage('Build') {
            steps {
                script { _ ->
                    docker.build(IMAGE_NAME, "-f ${DOCKERFILE_PATH} inventory_service")
                }
            }
        }

        stage('Test') {
            steps {
                script { _ ->
                    sh '''
                    # Run unit tests
                    cd inventory_service
                    python -m unittest discover -s tests
                    '''
                }
            }
        }

        stage('Push to Docker Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
                    script { _ ->
                        sh "echo $PASSWORD | docker login -u $USER --password-stdin"
                        sh "docker push ${IMAGE_NAME}"
                        sh "docker tag ${IMAGE_NAME} ${DOCKER_REPO}:latest"
                        sh "docker push ${DOCKER_REPO}:latest"
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
